server:
  port: 8076
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lfl-db1
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    #defer-datasource-initialization: true
  #sql:
  #  init:
   #   mode: always
  application:
    name: LFL76